### PR TITLE
Added prefix option

### PR DESCRIPTION
**Pull request by ponyesteves**
Hi, thank and congrats for the library. It' s very simple !

I'm working on a project that uses SOAP for exchanging data and I have the requirement of adding a prefix (namespace) in the tags. So I added the prefix option and perhaps it's usefull for someone else. 
I check the test and theres is only one failing but it's was failing before my changes. 
image

Check the code and suggest the corrections, I' ll ve glad on changing them.

### CODE REVIEW

**Comment by ponyesteves** [comment]
@michaelkourlas what do think about?

**Comment by michaelkourlas** [comment]
I'm actually working on a complete re-write of js2xmlparser at the moment, so I won't be merging in these changes directly. I'll see if I can ensure that an equivalent feature is available after the re-write, though.

**Comment by ponyesteves** [comment]
Great! 
Thanks

**Comment by michaelkourlas** [comment]
I'm going to close this PR since it can't be merged directly, but I'll consider adding a feature like this to a later release. Feel free to open an issue for it if you'd like.

**Pull request closed without merging**
